[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/movies/*"
  to = "/.netlify/functions/movies/:splat"
  status = 200

[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movies"
  status = 200
